// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YanKoltukBackend.Data;

#nullable disable

namespace YanKoltukBackend.Migrations
{
    [DbContext(typeof(YanKoltukDbContext))]
    [Migration("20241103160145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.ServiceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DropOffTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("PickupTime")
                        .HasColumnType("time");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StudentId");

                    b.ToTable("ServiceLogs");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Stewardess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stewardesses");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.StudentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GetOff_GetOn")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentServices");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Admin", b =>
                {
                    b.HasBaseType("YanKoltukBackend.Models.Entities.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Manager", b =>
                {
                    b.HasBaseType("YanKoltukBackend.Models.Entities.User");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.HasIndex("AdminId");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Parent", b =>
                {
                    b.HasBaseType("YanKoltukBackend.Models.Entities.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Service", b =>
                {
                    b.HasBaseType("YanKoltukBackend.Models.Entities.User");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StewardessId")
                        .HasColumnType("int");

                    b.HasIndex("DriverId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StewardessId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.ServiceLog", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.Service", "Service")
                        .WithMany("ServiceLogs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YanKoltukBackend.Models.Entities.Student", "Student")
                        .WithMany("ServiceLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Student", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.StudentService", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.Service", "Service")
                        .WithMany("StudentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YanKoltukBackend.Models.Entities.Student", "Student")
                        .WithMany("StudentServices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Admin", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("YanKoltukBackend.Models.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Manager", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.Admin", null)
                        .WithMany("Managers")
                        .HasForeignKey("AdminId");

                    b.HasOne("YanKoltukBackend.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("YanKoltukBackend.Models.Entities.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Parent", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("YanKoltukBackend.Models.Entities.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Service", b =>
                {
                    b.HasOne("YanKoltukBackend.Models.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YanKoltukBackend.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("YanKoltukBackend.Models.Entities.Service", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YanKoltukBackend.Models.Entities.Manager", null)
                        .WithMany("Services")
                        .HasForeignKey("ManagerId");

                    b.HasOne("YanKoltukBackend.Models.Entities.Stewardess", "Stewardess")
                        .WithMany()
                        .HasForeignKey("StewardessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Stewardess");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Student", b =>
                {
                    b.Navigation("ServiceLogs");

                    b.Navigation("StudentServices");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Admin", b =>
                {
                    b.Navigation("Managers");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Manager", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("YanKoltukBackend.Models.Entities.Service", b =>
                {
                    b.Navigation("ServiceLogs");

                    b.Navigation("StudentServices");
                });
#pragma warning restore 612, 618
        }
    }
}
